version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}exampleapi
    build:
      context: .
      dockerfile: Example.API/Dockerfile

  client:
    image: client
    build:
        context: ./example-client
        dockerfile: Dockerfile
  proxy:
    image: nginx:mainline
